const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('native', {
  getConfig: () => ipcRenderer.sendSync('cfg:get'),
  setConfig: (patch) => ipcRenderer.send('cfg:set', patch),
  getAppInfo: () => ipcRenderer.sendSync('app:info'),
  openExternal: (url) => ipcRenderer.send('open-external', url),
  openDataFolder: () => ipcRenderer.send('app:open-data-folder'),
  notify: (title, body) => ipcRenderer.send('notify', { title, body }),
  checkUpdate: () => ipcRenderer.invoke('upd:check'),
  updOpen: () => ipcRenderer.send('upd:open'),
  updClose: () => ipcRenderer.send('upd:close'),
  updDownload: () => ipcRenderer.invoke('upd:download'),
  updInstall: () => ipcRenderer.send('upd:install'),
  onUpdData: (cb) => ipcRenderer.on('upd:data', (_, v) => cb(v)),
  onUpdProgress: (cb) => ipcRenderer.on('upd:progress', (_, v) => cb(v)),
  toggleMaximize: () => ipcRenderer.send('win:maximize-toggle'),
  close: () => ipcRenderer.send('win:close'),
  toggleFullscreen: () => ipcRenderer.send('win:fullscreen'),
  trayAction: (a) => ipcRenderer.send('tray-action', a),
  onWinState: (cb) => ipcRenderer.on('win-state', (_, v) => cb(v)),
  onFsState: (cb) => ipcRenderer.on('fs-state', (_, v) => cb(v)),
  onOpenSettings: (cb) => ipcRenderer.on('open-settings', () => cb()),
  onMirrorPosters: (cb) => ipcRenderer.on('mirror-posters', (_, v) => cb(v)),
  onLoadProgress: (cb) => ipcRenderer.on('load-progress', (_, v) => cb(v)),
  setTaskbarProgress: (value) => ipcRenderer.send('taskbar-progress', value),
  diagnostics: () => ipcRenderer.invoke('app:diagnostics'),
  clearCache: () => ipcRenderer.invoke('app:clear-cache'),
  clearSiteData: () => ipcRenderer.invoke('app:clear-site-data'),
  connectionCheck: () => ipcRenderer.invoke('app:connection-check'),
  exportSettings: () => ipcRenderer.invoke('settings:export'),
  importSettings: () => ipcRenderer.invoke('settings:import'),
  resetSettings: () => ipcRenderer.invoke('settings:reset'),
  restartWebview: () => ipcRenderer.send('app:restart-webview'),
  toggleDevTools: () => ipcRenderer.send('app:toggle-devtools'),
  onRestartWebview: (cb) => ipcRenderer.on('restart-webview', () => cb()),
  onConfirmClose: (cb) => ipcRenderer.on('confirm-close', () => cb()),
  confirmClose: (ok) => ipcRenderer.send('app:confirm-close-result', ok),
  setPerformance: (mode) => ipcRenderer.send('app:set-performance', mode),
  taskbarOverlay: (kind) => ipcRenderer.send('app:taskbar-overlay', kind),
  onPerformanceMode: (cb) => ipcRenderer.on('performance-mode', (_, v) => cb(v)),
  setVolume: (delta) => ipcRenderer.send('media:volume', delta),
  getVolumeState: () => ipcRenderer.invoke('media:volume-state'),
  toggleMute: () => ipcRenderer.send('media:mute'),
  seek: (seconds) => ipcRenderer.send('media:seek', seconds),
  mediaAction: (action) => ipcRenderer.send('media:action', action),
  takeScreenshot: () => ipcRenderer.send('app:screenshot'),
  toggleAlwaysOnTop: () => ipcRenderer.send('app:always-on-top'),
  zoom: (delta) => ipcRenderer.send('app:zoom', delta),
  setHotkeys: (hotkeys) => ipcRenderer.invoke('hotkeys:set', hotkeys),
  registerHotkeys: () => ipcRenderer.send('app:register-hotkeys'),
  onAlwaysOnTop: (cb) => ipcRenderer.on('always-on-top', (_, v) => cb(v)),
  onToast: (cb) => ipcRenderer.on('toast', (_, v) => cb(v)),
  onMediaOverlay: (cb) => ipcRenderer.on('media-overlay', (_, v) => cb(v)),
  onOpenCommandPalette: (cb) => ipcRenderer.on('open-command-palette', () => cb()),
  onGoHome: (cb) => ipcRenderer.on('go-home', () => cb()),
  onSwitchSite: (cb) => ipcRenderer.on('switch-site', () => cb()),
});
