const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('native', {
  getConfig: () => ipcRenderer.sendSync('cfg:get'),
  setConfig: (patch) => ipcRenderer.send('cfg:set', patch),
  getAppInfo: () => ipcRenderer.sendSync('app:info'),
  openExternal: (url) => ipcRenderer.send('open-external', url),
  openDataFolder: () => ipcRenderer.send('app:open-data-folder'),
  notify: (title, body) => ipcRenderer.send('notify', { title, body }),
  checkUpdate: () => ipcRenderer.invoke('upd:check'),
  updOpen: () => ipcRenderer.send('upd:open'),
  updClose: () => ipcRenderer.send('upd:close'),
  updDownload: () => ipcRenderer.invoke('upd:download'),
  updInstall: () => ipcRenderer.send('upd:install'),
  onUpdData: (cb) => ipcRenderer.on('upd:data', (_, v) => cb(v)),
  onUpdProgress: (cb) => ipcRenderer.on('upd:progress', (_, v) => cb(v)),
  toggleMaximize: () => ipcRenderer.send('win:maximize-toggle'),
  close: () => ipcRenderer.send('win:close'),
  toggleFullscreen: () => ipcRenderer.send('win:fullscreen'),
  trayAction: (a) => ipcRenderer.send('tray-action', a),
  openDeepLink: (url) => ipcRenderer.send('open-external', url),
  onWinState: (cb) => ipcRenderer.on('win-state', (_, v) => cb(v)),
  onFsState: (cb) => ipcRenderer.on('fs-state', (_, v) => cb(v)),
  onOpenSettings: (cb) => ipcRenderer.on('open-settings', () => cb()),
  onMirrorPosters: (cb) => ipcRenderer.on('mirror-posters', (_, v) => cb(v)),
  onLoadProgress: (cb) => ipcRenderer.on('load-progress', (_, v) => cb(v)),
  setTaskbarProgress: (value) => ipcRenderer.send('taskbar-progress', value),
  diagnostics: () => ipcRenderer.invoke('app:diagnostics'),
  clearCache: () => ipcRenderer.invoke('app:clear-cache'),
  clearSiteData: () => ipcRenderer.invoke('app:clear-site-data'),
  connectionCheck: () => ipcRenderer.invoke('app:connection-check'),
  apiHealth: () => ipcRenderer.invoke('api:health'),
  apiGet: (path, query) => ipcRenderer.invoke('api:get', path, query),
  apiPost: (path, body) => ipcRenderer.invoke('api:post', path, body),
  apiRequest: (path, options) => ipcRenderer.invoke('api:request', path, options),
  apiSession: () => ipcRenderer.invoke('api:session'),
  animeSearch: (query, options) => ipcRenderer.invoke('animeon:search', query, options),
  animeFilters: () => ipcRenderer.invoke('animeon:filters'),
  animeSchedule: (options) => ipcRenderer.invoke('animeon:schedule', options),
  animeWatchingNow: (options) => ipcRenderer.invoke('animeon:watching-now', options),
  animeWatchlistCounts: () => ipcRenderer.invoke('animeon:watchlist-counts'),
  animeHistory: (options) => ipcRenderer.invoke('animeon:history', options),
  animeNotifications: (options) => ipcRenderer.invoke('animeon:notifications', options),
  libraryGet: () => ipcRenderer.invoke('library:get'),
  librarySet: (library) => ipcRenderer.invoke('library:set', library),
  libraryClearHistory: () => ipcRenderer.invoke('library:clear-history'),
  recentPages: () => ipcRenderer.invoke('pages:recent'),
  recentPageAdd: (item) => ipcRenderer.invoke('pages:recent-add', item),
  pageFavorites: () => ipcRenderer.invoke('pages:favorites'),
  togglePageFavorite: (item) => ipcRenderer.invoke('pages:favorite-toggle', item),
  tabsGet: () => ipcRenderer.invoke('tabs:get'),
  tabsSet: (tabs, active) => ipcRenderer.invoke('tabs:set', tabs, active),
  findInPage: (text, options) => ipcRenderer.invoke('find:start', text, options),
  stopFindInPage: () => ipcRenderer.invoke('find:stop'),
  setSleepTimer: (minutes, action) => ipcRenderer.invoke('sleep:set', minutes, action),
  getSleepTimer: () => ipcRenderer.invoke('sleep:get'),
  openLogs: () => ipcRenderer.invoke('logs:open'),
  getLogs: () => ipcRenderer.invoke('logs:get'),
  copyLogs: () => ipcRenderer.invoke('logs:copy'),
  clearLogs: () => ipcRenderer.invoke('logs:clear'),
  setDnd: (enabled) => ipcRenderer.invoke('dnd:set', enabled),
  cacheSettings: (patch) => ipcRenderer.invoke('cache:settings', patch),
  setMemorySaver: (enabled) => ipcRenderer.invoke('memory:saver', enabled),

  exportSettings: () => ipcRenderer.invoke('settings:export'),
  importSettings: () => ipcRenderer.invoke('settings:import'),
  resetSettings: () => ipcRenderer.invoke('settings:reset'),
  restartWebview: () => ipcRenderer.send('app:restart-webview'),
  toggleDevTools: () => ipcRenderer.send('app:toggle-devtools'),
  onRestartWebview: (cb) => ipcRenderer.on('restart-webview', () => cb()),
  onConfirmClose: (cb) => ipcRenderer.on('confirm-close', () => cb()),
  confirmClose: (ok) => ipcRenderer.send('app:confirm-close-result', ok),
  setPerformance: (mode) => ipcRenderer.send('app:set-performance', mode),
  taskbarOverlay: (kind) => ipcRenderer.send('app:taskbar-overlay', kind),
  onPerformanceMode: (cb) => ipcRenderer.on('performance-mode', (_, v) => cb(v)),
  siteMemory: () => ipcRenderer.invoke('site:memory'),
  systemStatus: () => ipcRenderer.invoke('system:status'),
  cacheInfo: () => ipcRenderer.invoke('system:cache-info'),
  clearApiCache: () => ipcRenderer.invoke('system:clear-api-cache'),
  getProfiles: () => ipcRenderer.invoke('profiles:get'),
  saveProfile: (name, data) => ipcRenderer.invoke('profiles:save', name, data),
  deleteProfile: (name) => ipcRenderer.invoke('profiles:delete', name),
  loadProfile: (name) => ipcRenderer.invoke('profiles:load', name),
  notificationPoll: () => ipcRenderer.invoke('animeon:notifications', { limit: 10 }),
  navigateSite: (url) => ipcRenderer.send('site:navigate', url),
  discordSetActivity: (data) => ipcRenderer.invoke('discord:setActivity', data),
  discordClearActivity: () => ipcRenderer.invoke('discord:clearActivity'),
  fetchSites: () => ipcRenderer.invoke('sites:fetch'),
  getSites: () => ipcRenderer.invoke('sites:get'),
  setVolume: (delta) => ipcRenderer.send('media:volume', delta),
  getVolumeState: () => ipcRenderer.invoke('media:volume-state'),
  toggleMute: () => ipcRenderer.send('media:mute'),
  seek: (seconds) => ipcRenderer.send('media:seek', seconds),
  mediaAction: (action) => ipcRenderer.send('media:action', action),
  getMediaState: () => ipcRenderer.invoke('media:state'),
  setPlaybackSpeed: (speed) => ipcRenderer.invoke('media:speed', speed),
  togglePiP: () => ipcRenderer.invoke('media:pip'),
  getPlaybackOptions: () => ipcRenderer.invoke('media:options'),
  selectPlaybackOption: (kind, value) => ipcRenderer.invoke('media:select-option', kind, value),
  smartSelectPlayback: (preferences) => ipcRenderer.invoke('media:smart-select', preferences),
  fallbackPlayback: (preferences) => ipcRenderer.invoke('media:fallback', preferences),
  onMediaState: (cb) => ipcRenderer.on('media-state', (_, v) => cb(v)),
  takeScreenshot: () => ipcRenderer.send('app:screenshot'),
  listScreenshots: () => ipcRenderer.invoke('screenshots:list'),
  getScreenshotThumb: (filePath) => ipcRenderer.invoke('screenshots:thumb', filePath),
  openScreenshot: (filePath) => ipcRenderer.invoke('screenshots:open', filePath),
  showScreenshotInFolder: (filePath) => ipcRenderer.invoke('screenshots:show', filePath),
  copyScreenshot: (filePath) => ipcRenderer.invoke('screenshots:copy', filePath),
  deleteScreenshot: (filePath) => ipcRenderer.invoke('screenshots:delete', filePath),
  openScreenshotsFolder: () => ipcRenderer.send('screenshots:open-folder'),
  onScreenshotsChanged: (cb) => ipcRenderer.on('screenshots:changed', () => cb()),
  toggleAlwaysOnTop: () => ipcRenderer.send('app:always-on-top'),
  zoom: (delta) => ipcRenderer.send('app:zoom', delta),
  applySiteCss: (css) => ipcRenderer.invoke('site:apply-css', css),
  setHotkeys: (hotkeys) => ipcRenderer.invoke('hotkeys:set', hotkeys),
  registerHotkeys: () => ipcRenderer.send('app:register-hotkeys'),
  onAlwaysOnTop: (cb) => ipcRenderer.on('always-on-top', (_, v) => cb(v)),
  onToast: (cb) => ipcRenderer.on('toast', (_, v) => cb(v)),
  onMediaOverlay: (cb) => ipcRenderer.on('media-overlay', (_, v) => cb(v)),
  onOpenCommandPalette: (cb) => ipcRenderer.on('open-command-palette', () => cb()),
  onGoHome: (cb) => ipcRenderer.on('go-home', () => cb()),
  onFindOpen: (cb) => ipcRenderer.on('find-open', () => cb()),
  onTabsCycle: (cb) => ipcRenderer.on('tabs-cycle', (_, v) => cb(v)),
  onSwitchSite: (cb) => ipcRenderer.on('switch-site', () => cb()),
});
